import type { Product } from "@/types/product.types";
import type { Transaction, DashboardStats, SalesChartData } from "@/types/sale.types";

// Mock Products - Hardware Store
export const mockProducts: Product[] = [
    {
        id: "1",
        sku: "FER-001",
        name: "Martillo Profesional Stanley",
        description: "Martillo de carpintero 16oz con mango de fibra de vidrio",
        category: "Herramientas",
        costPrice: 120.00,
        salePrice: 189.00,
        stock: 45,
        minStock: 5,
        status: "active",
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-12-01"),
    },
    {
        id: "2",
        sku: "FER-002",
        name: "Destornillador Phillips #2",
        description: "Destornillador de precisión con punta magnética",
        category: "Herramientas",
        costPrice: 35.00,
        salePrice: 55.00,
        stock: 3,
        minStock: 10,
        status: "active",
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-12-01"),
    },
    {
        id: "3",
        sku: "FER-003",
        name: "Cinta Métrica 5m Stanley",
        description: "Cinta métrica profesional con freno automático",
        category: "Herramientas",
        costPrice: 45.00,
        salePrice: 75.00,
        stock: 28,
        minStock: 8,
        status: "active",
        createdAt: new Date("2024-02-10"),
        updatedAt: new Date("2024-11-28"),
    },
    {
        id: "4",
        sku: "PIN-001",
        name: "Pintura Blanca Mate 4L",
        description: "Pintura acrílica para interiores, lavable",
        category: "Pinturas",
        costPrice: 180.00,
        salePrice: 280.00,
        stock: 15,
        minStock: 5,
        status: "active",
        createdAt: new Date("2024-03-01"),
        updatedAt: new Date("2024-12-05"),
    },
    {
        id: "5",
        sku: "FER-004",
        name: "Cerradura Phillips 500",
        description: "Cerradura de alta seguridad con 3 llaves",
        category: "Seguridad",
        costPrice: 320.00,
        salePrice: 489.00,
        stock: 8,
        minStock: 3,
        status: "active",
        createdAt: new Date("2024-02-20"),
        updatedAt: new Date("2024-12-01"),
    },
    {
        id: "6",
        sku: "PLO-001",
        name: 'Tubo PVC 4" x 6m',
        description: "Tubo de PVC para drenaje sanitario",
        category: "Plomería",
        costPrice: 85.00,
        salePrice: 129.00,
        stock: 32,
        minStock: 10,
        status: "active",
        createdAt: new Date("2024-01-25"),
        updatedAt: new Date("2024-11-30"),
    },
    {
        id: "7",
        sku: "ELE-001",
        name: "Cable 12 AWG Rojo (100m)",
        description: "Cable eléctrico THW calibre 12",
        category: "Electricidad",
        costPrice: 580.00,
        salePrice: 890.00,
        stock: 12,
        minStock: 5,
        status: "active",
        createdAt: new Date("2024-04-10"),
        updatedAt: new Date("2024-12-02"),
    },
    {
        id: "8",
        sku: "PIN-002",
        name: 'Brocha Premium 4"',
        description: "Brocha de cerda natural para pintura",
        category: "Pinturas",
        costPrice: 28.00,
        salePrice: 45.00,
        stock: 56,
        minStock: 15,
        status: "active",
        createdAt: new Date("2024-03-15"),
        updatedAt: new Date("2024-11-25"),
    },
    {
        id: "9",
        sku: "FER-005",
        name: 'Llave Inglesa Ajustable 12"',
        description: "Llave ajustable cromada profesional",
        category: "Herramientas",
        costPrice: 95.00,
        salePrice: 149.00,
        stock: 18,
        minStock: 5,
        status: "active",
        createdAt: new Date("2024-02-28"),
        updatedAt: new Date("2024-12-01"),
    },
    {
        id: "10",
        sku: "FER-006",
        name: "Silicón Transparente 280ml",
        description: "Sellador de silicón multiusos",
        category: "Ferretería General",
        costPrice: 42.00,
        salePrice: 68.00,
        stock: 65,
        minStock: 20,
        status: "active",
        createdAt: new Date("2024-05-01"),
        updatedAt: new Date("2024-11-28"),
    },
    {
        id: "11",
        sku: "FER-007",
        name: "Tornillos Galvanizados (100pz)",
        description: 'Tornillos para madera 2" con cabeza plana',
        category: "Ferretería General",
        costPrice: 28.00,
        salePrice: 45.00,
        stock: 120,
        minStock: 30,
        status: "active",
        createdAt: new Date("2024-01-10"),
        updatedAt: new Date("2024-12-03"),
    },
    {
        id: "12",
        sku: "FER-008",
        name: 'Clavos 2" (1kg)',
        description: "Clavos de acero para construcción",
        category: "Construcción",
        costPrice: 22.00,
        salePrice: 35.00,
        stock: 85,
        minStock: 25,
        status: "active",
        createdAt: new Date("2024-01-10"),
        updatedAt: new Date("2024-12-01"),
    },
    {
        id: "13",
        sku: "PLO-002",
        name: 'Llave de Paso 1/2"',
        description: "Válvula de bola cromada para agua",
        category: "Plomería",
        costPrice: 65.00,
        salePrice: 98.00,
        stock: 22,
        minStock: 8,
        status: "active",
        createdAt: new Date("2024-04-20"),
        updatedAt: new Date("2024-11-30"),
    },
    {
        id: "14",
        sku: "ELE-002",
        name: "Interruptor Doble Blanco",
        description: "Interruptor de pared decorativo",
        category: "Electricidad",
        costPrice: 35.00,
        salePrice: 58.00,
        stock: 45,
        minStock: 15,
        status: "active",
        createdAt: new Date("2024-05-15"),
        updatedAt: new Date("2024-12-02"),
    },
    {
        id: "15",
        sku: "JAR-001",
        name: "Manguera 15m Reforzada",
        description: "Manguera de jardín con conectores",
        category: "Jardinería",
        costPrice: 120.00,
        salePrice: 189.00,
        stock: 0,
        minStock: 5,
        status: "active",
        createdAt: new Date("2024-06-01"),
        updatedAt: new Date("2024-11-20"),
    },
    {
        id: "16",
        sku: "CON-001",
        name: "Cemento Gris 50kg",
        description: "Cemento Portland tipo I",
        category: "Construcción",
        costPrice: 180.00,
        salePrice: 245.00,
        stock: 48,
        minStock: 20,
        status: "active",
        createdAt: new Date("2024-03-20"),
        updatedAt: new Date("2024-12-05"),
    },
    {
        id: "17",
        sku: "SEG-001",
        name: "Candado Reforzado 60mm",
        description: "Candado de latón con 3 llaves",
        category: "Seguridad",
        costPrice: 85.00,
        salePrice: 135.00,
        stock: 25,
        minStock: 8,
        status: "active",
        createdAt: new Date("2024-04-05"),
        updatedAt: new Date("2024-12-01"),
    },
    {
        id: "18",
        sku: "FER-009",
        name: "Taladro Percutor 750W",
        description: "Taladro eléctrico con velocidad variable",
        category: "Herramientas",
        costPrice: 850.00,
        salePrice: 1250.00,
        stock: 4,
        minStock: 2,
        status: "active",
        createdAt: new Date("2024-02-15"),
        updatedAt: new Date("2024-12-04"),
    },
    {
        id: "19",
        sku: "PIN-003",
        name: "Rodillo de Pintura 9\"",
        description: "Rodillo con felpa de alta densidad",
        category: "Pinturas",
        costPrice: 45.00,
        salePrice: 75.00,
        stock: 38,
        minStock: 12,
        status: "active",
        createdAt: new Date("2024-03-25"),
        updatedAt: new Date("2024-11-28"),
    },
    {
        id: "20",
        sku: "ELE-003",
        name: "Extensión Eléctrica 10m",
        description: "Extensión con 3 tomas y protector",
        category: "Electricidad",
        costPrice: 120.00,
        salePrice: 185.00,
        stock: 15,
        minStock: 5,
        status: "active",
        createdAt: new Date("2024-05-30"),
        updatedAt: new Date("2024-12-02"),
    },
    {
        id: "21",
        sku: "PLO-003",
        name: 'Codo PVC 4" 90°',
        description: "Accesorio de PVC para drenaje",
        category: "Plomería",
        costPrice: 18.00,
        salePrice: 32.00,
        stock: 78,
        minStock: 25,
        status: "active",
        createdAt: new Date("2024-04-15"),
        updatedAt: new Date("2024-11-30"),
    },
    {
        id: "22",
        sku: "FER-010",
        name: "Nivel de Burbuja 24\"",
        description: "Nivel de aluminio profesional",
        category: "Herramientas",
        costPrice: 85.00,
        salePrice: 135.00,
        stock: 12,
        minStock: 4,
        status: "active",
        createdAt: new Date("2024-06-10"),
        updatedAt: new Date("2024-12-01"),
    },
    {
        id: "23",
        sku: "JAR-002",
        name: "Tijera de Podar",
        description: "Tijera para jardinería con mango ergonómico",
        category: "Jardinería",
        costPrice: 55.00,
        salePrice: 89.00,
        stock: 20,
        minStock: 6,
        status: "active",
        createdAt: new Date("2024-07-01"),
        updatedAt: new Date("2024-11-25"),
    },
    {
        id: "24",
        sku: "CON-002",
        name: "Arena Fina (Saco 40kg)",
        description: "Arena lavada para construcción",
        category: "Construcción",
        costPrice: 45.00,
        salePrice: 75.00,
        stock: 60,
        minStock: 30,
        status: "active",
        createdAt: new Date("2024-03-30"),
        updatedAt: new Date("2024-12-05"),
    }
];

// Mock Transactions for Dashboard
export const mockTransactions: Transaction[] = [
    {
        id: "TRX-001",
        type: "sale",
        description: "Venta #1234",
        amount: 1250.00,
        method: "cash",
        timestamp: new Date(Date.now() - 5 * 60 * 1000), // 5 min ago
    },
    {
        id: "TRX-002",
        type: "expense",
        description: "Compra proveedor - Pinturas",
        amount: 3500.00,
        timestamp: new Date(Date.now() - 25 * 60 * 1000), // 25 min ago
    },
    {
        id: "TRX-003",
        type: "sale",
        description: "Venta #1233",
        amount: 489.00,
        method: "card",
        timestamp: new Date(Date.now() - 45 * 60 * 1000), // 45 min ago
    },
    {
        id: "TRX-004",
        type: "sale",
        description: "Venta #1232",
        amount: 2150.00,
        method: "cash",
        timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000), // 2 hours ago
    },
    {
        id: "TRX-005",
        type: "expense",
        description: "Pago servicios - Electricidad",
        amount: 1200.00,
        timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000), // 3 hours ago
    },
    {
        id: "TRX-006",
        type: "sale",
        description: "Venta #1231",
        amount: 756.00,
        method: "qr",
        timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000), // 5 hours ago
    },
    {
        id: "TRX-007",
        type: "refund",
        description: "Devolución #REF-012",
        amount: 189.00,
        timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000), // 6 hours ago
    },
    {
        id: "TRX-008",
        type: "sale",
        description: "Venta #1230",
        amount: 3200.00,
        method: "card",
        timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000), // 8 hours ago
    },
];

// Dashboard Stats
export const mockDashboardStats: DashboardStats = {
    todaySales: 12450.00,
    todayOrders: 48,
    lowStockProducts: 12,
    netProfit: 4320.00,
    salesGrowth: 12.5,
    ordersGrowth: 8,
    profitGrowth: 5.2,
};

// Sales vs Expenses Chart Data (Last 7 days)
export const mockSalesChartData: SalesChartData[] = [
    { day: "Lun", sales: 4200, expenses: 2100 },
    { day: "Mar", sales: 3800, expenses: 1800 },
    { day: "Mié", sales: 5200, expenses: 2400 },
    { day: "Jue", sales: 4600, expenses: 1950 },
    { day: "Vie", sales: 6800, expenses: 3200 },
    { day: "Sáb", sales: 8500, expenses: 2800 },
    { day: "Dom", sales: 3200, expenses: 1200 },
];
